apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iue2d9vns-python
  janus-idp.io/tekton: iue2d9vns-python
  backstage.io/kubernetes-id: iue2d9vns-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iue2d9vns-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
