apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iue2d9vns-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iue2d9vns-python 
  name: iue2d9vns-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iue2d9vns-python 
